// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9nzfP9k0CQNOsEFSoiHyt3b9U8i_td60',
    appId: '1:94638179566:web:64e07edcad449bf1831fff',
    messagingSenderId: '94638179566',
    projectId: 'hire-service-fe69d',
    authDomain: 'hire-service-fe69d.firebaseapp.com',
    storageBucket: 'hire-service-fe69d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMft4_E3DDmBlsk7xtdr0C66Nw-6pqt3k',
    appId: '1:94638179566:android:878a1a010da8c703831fff',
    messagingSenderId: '94638179566',
    projectId: 'hire-service-fe69d',
    storageBucket: 'hire-service-fe69d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86CqXUn31CVA6pcd0QL_o__GuStYTKTM',
    appId: '1:94638179566:ios:c578ea1522ea398e831fff',
    messagingSenderId: '94638179566',
    projectId: 'hire-service-fe69d',
    storageBucket: 'hire-service-fe69d.firebasestorage.app',
    iosBundleId: 'com.gulzarsoft.hireservice',
  );
}
